// <Auto-Generated/>
using System.Buffers;

namespace Cuture.AspNetCore.ResponseCaching.Internal;

internal readonly ref struct PooledReadOnlyCharSpan
{
    #region Private 字段

    private readonly char[]? _pooledValue;

    #endregion Private 字段

    #region Public 属性

    public ReadOnlySpan<char> Value { get; }

    #endregion Public 属性

    #region Public 构造函数

    public PooledReadOnlyCharSpan(char[]? pooledValue, ReadOnlySpan<char> value)
    {
        _pooledValue = pooledValue;
        Value = value;
    }

    #endregion Public 构造函数

    #region Public 方法

    public void Dispose()
    {
        if (_pooledValue is not null)
        {
            //Hack 重复调用检查？
            ArrayPool<char>.Shared.Return(_pooledValue, false);
        }
    }

    /// <summary>
    /// 转换为字符串
    /// </summary>
    /// <returns></returns>
    public override string ToString()
    {
        return new string(Value);
    }

    #endregion Public 方法
}
